### ISSUE TITLE
创建数据模型定义报属性没有初始化表达式

### ISSUE THREAD

**Issue by iiuhuy** [tuture-dev/koa-quickstart#1]
属性“id”没有初始化表达式，且未在构造函数中明确赋值。ts(2564)

![image](https://user-images.githubusercontent.com/21032217/105487828-acbbf080-5ceb-11eb-998b-1fa329e7134d.png)

是断言处理一下就好了嘛，还是需要如何配置一下呢？

![image](https://user-images.githubusercontent.com/21032217/105487904-ce1cdc80-5ceb-11eb-84b1-fd7cb8f94999.png)

**Comment by pftom** [comment]
@AlvinMi 能解决能用就 ok 啦
